POST localhost:8080/api/people
Content-Type: application/json

{
  "name": "Aidar",
  "surname": "Yarullin",
  "patronymic": "Lenarovich"
}

###
DELETE localhost:8080/api/people?id=018d2687-0a96-79d2-960b-4c5d1345685c

###

PUT localhost:8080/api/people?id=018d1e1c-8cbb-70f6-b01e-699687167962
Content-Type: application/json

{
  "name": "Ildar",
  "surname": "Yarullin",
  "patronymic": "Lenarovich"
}