POST localhost:8080/api/people
Content-Type: application/json

{
  "name": "Aidar",
  "surname": "Yarullin",
  "patronymic": "Lenarovich"
}

###
DELETE localhost:8080/api/people?id=018d2b4b-d410-72b5-a172-c79e63c969a0

###

PUT localhost:8080/api/people?id=018d1e1c-8cbb-70f6-b01e-699687167962
Content-Type: application/json

{
  "name": "Aidar",
  "surname": "Yarullin",
  "patronymic": "Lenarovich",
  "age": 29
}

###
POST localhost:8080/api/people
Content-Type: application/json

{
  "name": "Islam",
  "surname": "Askerov",
  "patronymic": "Vladimirovich"
}