POST localhost:8080/api/people
Content-Type: application/json

{
  "name": "Aidar",
  "surname": "Yarullin",
  "patronymic": "Lenarovich"
}

###
DELETE localhost:8080/api/people?id=018d2b4b-d410-72b5-a172-c79e63c969a0

###

PUT localhost:8080/api/people?id=018d2cb4-4ad8-704d-8435-1a1ffb50a697
Content-Type: application/json

{
  "name": "Aidar",
  "surname": "Askerov",
  "patronymic": "Vladimirovich"
}

###
POST localhost:8080/api/people
Content-Type: application/json

{
  "name": "Islam",
  "surname": "Askerov",
  "patronymic": "Vladimirovich"
}

###
GET localhost:8080/api/people?name=Aidar&nationality=KZ&limit=10&offset=0