POST localhost:8080/api/people
Content-Type: application/json

{
  "name": "Aidar",
  "surname": "Neyarullin",
  "patronymic": "Lenarovich"
}

###
DELETE localhost:8080/api/people?id=018d2de0-5b58-7de5-b829-20592d8c5a86

###

PUT localhost:8080/api/people?id=018d2de0-5b58-7de5-b829-20592d8c5a86
Content-Type: application/json

{
  "name": "Aidar",
  "surname": "Askerov",
  "patronymic": "Vladimirovich",
  "age": 29
}

###
POST localhost:8080/api/people
Content-Type: application/json

{
  "name": "Islam",
  "surname": "Askerov",
  "patronymic": "Vladimirovich"
}

###
GET localhost:8080/api/people?name=Aidar&nationality=KZ&limit=10&offset=0