POST localhost:8080/api/people
Content-Type: application/json

{
  "name": "Aidar",
  "surname": "Yarullin",
  "patronymic": "Lenarovich"
}

###
DELETE localhost:8080/api/people?id=018d3028-1aa5-7904-aebf-a223c64b4316

###

PUT localhost:8080/api/people?id=018d3028-1aa5-7904-aebf-a223c64b4316
Content-Type: application/json

{
  "name": "Aidar",
  "surname": "Askerov",
  "patronymic": "Vladimirovich",
  "age": 29,
  "nationality": "KZ"
}

###
POST localhost:8080/api/people
Content-Type: application/json

{
  "name": "Islam",
  "surname": "Askerov",
  "patronymic": "Vladimirovich"
}

###
GET localhost:8080/api/people?name=Aidar&nationality=KZ&limit=10&offset=0